In [2]:
# 출국장 현황 (API : D-0 ~ D+1)
# https://www.data.go.kr/data/15095066/openapi.do

import requests
import json
import pandas as pd

for i in [0, 1]:

    url = 'http://apis.data.go.kr/B551177/passgrAnncmt/getPassgrAnncmt'
    params ={'serviceKey' : 'Uqidzm0Dr63+s0XrNpvf/I4NFhx9jc5yjvBfX30vi8PuDLFwacnhW//3rG0LszGt8kssHj3W4BYkGmnjWdNjrA==',
            'type' : 'json',
            'selectdate' : i,    # 0: 오늘, 1: 내일
             'numOfRows' : 100
            }

    response = requests.get(url, params=params)

    # 응답 상태 코드 출력
    print(f"HTTP 상태 코드: {response.status_code}")

    # 응답 내용 출력
    print("응답 내용:")
    print(response.text)

    try:
        # JSON 데이터를 파싱
        jsonObj = response.json()

        # JSON 데이터에서 원하는 값들만 출력
        items = jsonObj['response']['body']['items']
        df = pd.DataFrame(items)
        df = df[['adate', 'atime', 
                 't1dg1', 't1dg2', 't1dg3', 't1dg4', 't1dg5', 't1dg6', 't1dgsum1',
                 't2dg1', 't2dg2', 't2dgsum2']]
        df = df.rename(columns={'t1dg1': 'T1(1)', 
                                't1dg2': 'T1(2)', 
                                't1dg3': 'T1(3)', 
                                't1dg4': 'T1(4)',
                                't1dg5': 'T1(5)',
                                't1dg6': 'T1(6)',
                                't1dgsum1': 'T1',
                                't2dg1': 'T2(A)', 
                                't2dg2': 'T2(B)', 
                                't2dgsum2': 'T2'
                               })

        df = df.astype({'T1(1)': 'float', 'T1(2)': 'float', 'T1(3)': 'float', 'T1(4)': 'float', 'T1(5)': 'float', 'T1(6)': 'float', 'T1': 'float',
                        'T2(A)': 'float', 'T2(B)': 'float', 'T2': 'float'})
        df = df.astype({'T1(1)': 'int', 'T1(2)': 'int', 'T1(3)': 'int', 'T1(4)': 'int', 'T1(5)': 'int', 'T1(6)': 'int', 'T1': 'int',
                        'T2(A)': 'int', 'T2(B)': 'int', 'T2': 'int'})

        display(df)

    except ValueError as e:
        print("JSON 파싱 오류:", e)
        jsonObj = {}

HTTP 상태 코드: 200
응답 내용:
{"response":{"header":{"resultCode":"00","resultMsg":"NORMAL SERVICE."},"body":{"numOfRows":100,"pageNo":1,"totalCount":25,"items":[{"adate":"20260429","atime":"00_01","t1eg1":"187.0","t1eg2":"0.0","t1eg3":"319.0","t1eg4":"0.0","t1egsum1":"506.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"425.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"425.0","t2eg1":"0.0","t2eg2":"0.0","t2egsum1":"0.0","t2dg1":"0.0","t2dg2":"0.0","t2dgsum2":"0.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"01_02","t1eg1":"135.0","t1eg2":"0.0","t1eg3":"358.0","t1eg4":"0.0","t1egsum1":"493.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"128.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"128.0","t2eg1":"0.0","t2eg2":"0.0","t2egsum1":"0.0","t2dg1":"0.0","t2dg2":"0.0","t2dgsum2":"0.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"02_03","t1eg1":"33.0","t1eg2":"0.0","t1eg3":"162.0","t1eg4":"0.0","t1egsum1":"195.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"50.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"50.0","t2eg1":"90.0","t2eg2":"0.0","t2egsum1":"90.0","t2dg1":"2.0","t2dg2":"0.0","t2dgsum2":"2.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"03_04","t1eg1":"130.0","t1eg2":"0.0","t1eg3":"0.0","t1eg4":"0.0","t1egsum1":"130.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"144.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"144.0","t2eg1":"133.0","t2eg2":"0.0","t2egsum1":"133.0","t2dg1":"61.0","t2dg2":"0.0","t2dgsum2":"61.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"04_05","t1eg1":"327.0","t1eg2":"0.0","t1eg3":"372.0","t1eg4":"0.0","t1egsum1":"699.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"632.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"632.0","t2eg1":"1436.0","t2eg2":"0.0","t2egsum1":"1436.0","t2dg1":"583.0","t2dg2":"0.0","t2dgsum2":"583.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"05_06","t1eg1":"608.0","t1eg2":"0.0","t1eg3":"1162.0","t1eg4":"0.0","t1egsum1":"1770.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"1846.0","t1dg4":"0.0","t1dg5":"86.0","t1dg6":"0.0","t1dgsum1":"1932.0","t2eg1":"893.0","t2eg2":"1527.0","t2egsum1":"2420.0","t2dg1":"1691.0","t2dg2":"627.0","t2dgsum2":"2318.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"06_07","t1eg1":"290.0","t1eg2":"0.0","t1eg3":"643.0","t1eg4":"944.0","t1egsum1":"1877.0","t1dg1":"0.0","t1dg2":"1121.0","t1dg3":"1446.0","t1dg4":"622.0","t1dg5":"168.0","t1dg6":"0.0","t1dgsum1":"3357.0","t2eg1":"360.0","t2eg2":"1438.0","t2egsum1":"1798.0","t2dg1":"2205.0","t2dg2":"1673.0","t2dgsum2":"3878.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"07_08","t1eg1":"668.0","t1eg2":"834.0","t1eg3":"370.0","t1eg4":"606.0","t1egsum1":"2478.0","t1dg1":"0.0","t1dg2":"1501.0","t1dg3":"1178.0","t1dg4":"1180.0","t1dg5":"175.0","t1dg6":"0.0","t1dgsum1":"4034.0","t2eg1":"592.0","t2eg2":"1141.0","t2egsum1":"1733.0","t2dg1":"2585.0","t2dg2":"1827.0","t2dgsum2":"4412.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"08_09","t1eg1":"43.0","t1eg2":"1020.0","t1eg3":"687.0","t1eg4":"794.0","t1egsum1":"2544.0","t1dg1":"0.0","t1dg2":"1605.0","t1dg3":"1189.0","t1dg4":"1161.0","t1dg5":"206.0","t1dg6":"0.0","t1dgsum1":"4161.0","t2eg1":"561.0","t2eg2":"952.0","t2egsum1":"1513.0","t2dg1":"2483.0","t2dg2":"1460.0","t2dgsum2":"3943.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"09_10","t1eg1":"253.0","t1eg2":"440.0","t1eg3":"151.0","t1eg4":"1.0","t1egsum1":"845.0","t1dg1":"0.0","t1dg2":"1430.0","t1dg3":"1125.0","t1dg4":"1104.0","t1dg5":"185.0","t1dg6":"0.0","t1dgsum1":"3844.0","t2eg1":"227.0","t2eg2":"1166.0","t2egsum1":"1393.0","t2dg1":"1483.0","t2dg2":"856.0","t2dgsum2":"2339.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"10_11","t1eg1":"174.0","t1eg2":"685.0","t1eg3":"416.0","t1eg4":"462.0","t1egsum1":"1737.0","t1dg1":"0.0","t1dg2":"1133.0","t1dg3":"1132.0","t1dg4":"1351.0","t1dg5":"202.0","t1dg6":"0.0","t1dgsum1":"3818.0","t2eg1":"0.0","t2eg2":"136.0","t2egsum1":"136.0","t2dg1":"1361.0","t2dg2":"1095.0","t2dgsum2":"2456.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"11_12","t1eg1":"706.0","t1eg2":"1097.0","t1eg3":"841.0","t1eg4":"729.0","t1egsum1":"3373.0","t1dg1":"0.0","t1dg2":"937.0","t1dg3":"1008.0","t1dg4":"1175.0","t1dg5":"170.0","t1dg6":"0.0","t1dgsum1":"3290.0","t2eg1":"346.0","t2eg2":"359.0","t2egsum1":"705.0","t2dg1":"1468.0","t2dg2":"991.0","t2dgsum2":"2459.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"12_13","t1eg1":"364.0","t1eg2":"599.0","t1eg3":"660.0","t1eg4":"741.0","t1egsum1":"2364.0","t1dg1":"0.0","t1dg2":"864.0","t1dg3":"913.0","t1dg4":"1004.0","t1dg5":"135.0","t1dg6":"0.0","t1dgsum1":"2916.0","t2eg1":"439.0","t2eg2":"1124.0","t2egsum1":"1563.0","t2dg1":"1091.0","t2dg2":"840.0","t2dgsum2":"1931.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"13_14","t1eg1":"773.0","t1eg2":"1150.0","t1eg3":"630.0","t1eg4":"652.0","t1egsum1":"3205.0","t1dg1":"0.0","t1dg2":"776.0","t1dg3":"896.0","t1dg4":"1032.0","t1dg5":"153.0","t1dg6":"0.0","t1dgsum1":"2857.0","t2eg1":"611.0","t2eg2":"928.0","t2egsum1":"1539.0","t2dg1":"1173.0","t2dg2":"922.0","t2dgsum2":"2095.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"14_15","t1eg1":"1056.0","t1eg2":"928.0","t1eg3":"819.0","t1eg4":"773.0","t1egsum1":"3576.0","t1dg1":"0.0","t1dg2":"632.0","t1dg3":"713.0","t1dg4":"805.0","t1dg5":"117.0","t1dg6":"0.0","t1dgsum1":"2267.0","t2eg1":"1328.0","t2eg2":"1834.0","t2egsum1":"3162.0","t2dg1":"1326.0","t2dg2":"1023.0","t2dgsum2":"2349.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"15_16","t1eg1":"230.0","t1eg2":"775.0","t1eg3":"650.0","t1eg4":"1294.0","t1egsum1":"2949.0","t1dg1":"0.0","t1dg2":"933.0","t1dg3":"754.0","t1dg4":"763.0","t1dg5":"121.0","t1dg6":"0.0","t1dgsum1":"2571.0","t2eg1":"1278.0","t2eg2":"1594.0","t2egsum1":"2872.0","t2dg1":"884.0","t2dg2":"596.0","t2dgsum2":"1480.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"16_17","t1eg1":"807.0","t1eg2":"1114.0","t1eg3":"788.0","t1eg4":"505.0","t1egsum1":"3214.0","t1dg1":"0.0","t1dg2":"1031.0","t1dg3":"706.0","t1dg4":"653.0","t1dg5":"93.0","t1dg6":"0.0","t1dgsum1":"2483.0","t2eg1":"2178.0","t2eg2":"2085.0","t2egsum1":"4263.0","t2dg1":"1454.0","t2dg2":"742.0","t2dgsum2":"2196.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"17_18","t1eg1":"629.0","t1eg2":"608.0","t1eg3":"635.0","t1eg4":"264.0","t1egsum1":"2136.0","t1dg1":"0.0","t1dg2":"876.0","t1dg3":"670.0","t1dg4":"681.0","t1dg5":"73.0","t1dg6":"0.0","t1dgsum1":"2300.0","t2eg1":"1908.0","t2eg2":"1784.0","t2egsum1":"3692.0","t2dg1":"2122.0","t2dg2":"1698.0","t2dgsum2":"3820.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"18_19","t1eg1":"1273.0","t1eg2":"475.0","t1eg3":"192.0","t1eg4":"411.0","t1egsum1":"2351.0","t1dg1":"0.0","t1dg2":"741.0","t1dg3":"719.0","t1dg4":"790.0","t1dg5":"89.0","t1dg6":"0.0","t1dgsum1":"2339.0","t2eg1":"1445.0","t2eg2":"2488.0","t2egsum1":"3933.0","t2dg1":"1830.0","t2dg2":"1760.0","t2dgsum2":"3590.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"19_20","t1eg1":"504.0","t1eg2":"953.0","t1eg3":"528.0","t1eg4":"744.0","t1egsum1":"2729.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"1707.0","t1dg4":"921.0","t1dg5":"148.0","t1dg6":"0.0","t1dgsum1":"2776.0","t2eg1":"1143.0","t2eg2":"1619.0","t2egsum1":"2762.0","t2dg1":"2321.0","t2dg2":"0.0","t2dgsum2":"2321.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"20_21","t1eg1":"593.0","t1eg2":"557.0","t1eg3":"1040.0","t1eg4":"644.0","t1egsum1":"2834.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"2016.0","t1dg4":"0.0","t1dg5":"140.0","t1dg6":"0.0","t1dgsum1":"2156.0","t2eg1":"1034.0","t2eg2":"643.0","t2egsum1":"1677.0","t2dg1":"1052.0","t2dg2":"0.0","t2dgsum2":"1052.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"21_22","t1eg1":"639.0","t1eg2":"728.0","t1eg3":"404.0","t1eg4":"744.0","t1egsum1":"2515.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"1005.0","t1dg4":"0.0","t1dg5":"78.0","t1dg6":"0.0","t1dgsum1":"1083.0","t2eg1":"2133.0","t2eg2":"824.0","t2egsum1":"2957.0","t2dg1":"622.0","t2dg2":"0.0","t2dgsum2":"622.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"22_23","t1eg1":"971.0","t1eg2":"598.0","t1eg3":"1229.0","t1eg4":"516.0","t1egsum1":"3314.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"665.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"665.0","t2eg1":"1067.0","t2eg2":"417.0","t2egsum1":"1484.0","t2dg1":"212.0","t2dg2":"0.0","t2dgsum2":"212.0","tmp1":"","tmp2":""},{"adate":"20260429","atime":"23_00","t1eg1":"120.0","t1eg2":"0.0","t1eg3":"488.0","t1eg4":"0.0","t1egsum1":"608.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"280.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"280.0","t2eg1":"1066.0","t2eg2":"0.0","t2egsum1":"1066.0","t2dg1":"3.0","t2dg2":"0.0","t2dgsum2":"3.0","tmp1":"","tmp2":""},{"adate":"합계","atime":"합계","t1eg1":"11513.0","t1eg2":"12561.0","t1eg3":"13544.0","t1eg4":"10824.0","t1egsum1":"48442.0","t1dg1":"0.0","t1dg2":"13580.0","t1dg3":"21347.0","t1dg4":"13242.0","t1dg5":"2339.0","t1dg6":"0.0","t1dgsum1":"50508.0","t2eg1":"20268.0","t2eg2":"22059.0","t2egsum1":"42327.0","t2dg1":"28012.0","t2dg2":"16110.0","t2dgsum2":"44122.0","tmp1":"","tmp2":""}]}}}

,adate,atime,T1(1),T1(2),T1(3),T1(4),T1(5),T1(6),T1,T2(A),T2(B),T2
0,20260429,00_01,0,0,425,0,0,0,425,0,0,0
1,20260429,01_02,0,0,128,0,0,0,128,0,0,0
2,20260429,02_03,0,0,50,0,0,0,50,2,0,2
3,20260429,03_04,0,0,144,0,0,0,144,61,0,61
4,20260429,04_05,0,0,632,0,0,0,632,583,0,583
5,20260429,05_06,0,0,1846,0,86,0,1932,1691,627,2318
6,20260429,06_07,0,1121,1446,622,168,0,3357,2205,1673,3878
7,20260429,07_08,0,1501,1178,1180,175,0,4034,2585,1827,4412
8,20260429,08_09,0,1605,1189,1161,206,0,4161,2483,1460,3943
9,20260429,09_10,0,1430,1125,1104,185,0,3844,1483,856,2339
10,20260429,10_11,0,1133,1132,1351,202,0,3818,1361,1095,2456
11,20260429,11_12,0,937,1008,1175,170,0,3290,1468,991,2459
12,20260429,12_13,0,864,913,1004,135,0,2916,1091,840,1931
13,20260429,13_14,0,776,896,1032,153,0,2857,1173,922,2095
14,20260429,14_15,0,632,713,805,117,0,2267,1326,1023,2349
15,20260429,15_16,0,933,754,763,121,0,2571,884,596,1480
16,20260429,16_17,0,1031,706,653,93,0,2483,1454,742,2196
17,20260429,17_18,0,876,670,681,73,0,2300,2122,1698,3820
18,20260429,18_19,0,741,719,790,89,0,2339,1830,1760,3590
19,20260429,19_20,0,0,1707,921,148,0,2776,2321,0,2321
20,20260429,20_21,0,0,2016,0,140,0,2156,1052,0,1052
21,20260429,21_22,0,0,1005,0,78,0,1083,622,0,622
22,20260429,22_23,0,0,665,0,0,0,665,212,0,212
23,20260429,23_00,0,0,280,0,0,0,280,3,0,3
24,합계,합계,0,13580,21347,13242,2339,0,50508,28012,16110,44122

HTTP 상태 코드: 200
응답 내용:
{"response":{"header":{"resultCode":"00","resultMsg":"NORMAL SERVICE."},"body":{"numOfRows":100,"pageNo":1,"totalCount":25,"items":[{"adate":"20260430","atime":"00_01","t1eg1":"202.0","t1eg2":"0.0","t1eg3":"452.0","t1eg4":"0.0","t1egsum1":"654.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"496.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"496.0","t2eg1":"0.0","t2eg2":"0.0","t2egsum1":"0.0","t2dg1":"0.0","t2dg2":"0.0","t2dgsum2":"0.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"01_02","t1eg1":"0.0","t1eg2":"0.0","t1eg3":"382.0","t1eg4":"0.0","t1egsum1":"382.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"190.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"190.0","t2eg1":"0.0","t2eg2":"0.0","t2egsum1":"0.0","t2dg1":"0.0","t2dg2":"0.0","t2dgsum2":"0.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"02_03","t1eg1":"63.0","t1eg2":"0.0","t1eg3":"327.0","t1eg4":"0.0","t1egsum1":"390.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"56.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"56.0","t2eg1":"88.0","t2eg2":"0.0","t2egsum1":"88.0","t2dg1":"4.0","t2dg2":"0.0","t2dgsum2":"4.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"03_04","t1eg1":"0.0","t1eg2":"0.0","t1eg3":"0.0","t1eg4":"0.0","t1egsum1":"0.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"157.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"157.0","t2eg1":"3.0","t2eg2":"0.0","t2egsum1":"3.0","t2dg1":"73.0","t2dg2":"0.0","t2dgsum2":"73.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"04_05","t1eg1":"338.0","t1eg2":"0.0","t1eg3":"188.0","t1eg4":"0.0","t1egsum1":"526.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"905.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"905.0","t2eg1":"623.0","t2eg2":"0.0","t2egsum1":"623.0","t2dg1":"687.0","t2dg2":"0.0","t2dgsum2":"687.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"05_06","t1eg1":"925.0","t1eg2":"0.0","t1eg3":"769.0","t1eg4":"0.0","t1egsum1":"1694.0","t1dg1":"0.0","t1dg2":"359.0","t1dg3":"1888.0","t1dg4":"0.0","t1dg5":"98.0","t1dg6":"0.0","t1dgsum1":"2345.0","t2eg1":"1593.0","t2eg2":"1464.0","t2egsum1":"3057.0","t2dg1":"1522.0","t2dg2":"1255.0","t2dgsum2":"2777.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"06_07","t1eg1":"723.0","t1eg2":"0.0","t1eg3":"485.0","t1eg4":"1062.0","t1egsum1":"2270.0","t1dg1":"0.0","t1dg2":"1002.0","t1dg3":"902.0","t1dg4":"1163.0","t1dg5":"167.0","t1dg6":"0.0","t1dgsum1":"3234.0","t2eg1":"316.0","t2eg2":"1651.0","t2egsum1":"1967.0","t2dg1":"2651.0","t2dg2":"2025.0","t2dgsum2":"4676.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"07_08","t1eg1":"1593.0","t1eg2":"1352.0","t1eg3":"465.0","t1eg4":"464.0","t1egsum1":"3874.0","t1dg1":"0.0","t1dg2":"1372.0","t1dg3":"1124.0","t1dg4":"1139.0","t1dg5":"173.0","t1dg6":"0.0","t1dgsum1":"3808.0","t2eg1":"1272.0","t2eg2":"1527.0","t2egsum1":"2799.0","t2dg1":"2965.0","t2dg2":"2017.0","t2dgsum2":"4982.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"08_09","t1eg1":"1356.0","t1eg2":"836.0","t1eg3":"48.0","t1eg4":"48.0","t1egsum1":"2288.0","t1dg1":"0.0","t1dg2":"1397.0","t1dg3":"1187.0","t1dg4":"1255.0","t1dg5":"221.0","t1dg6":"0.0","t1dgsum1":"4060.0","t2eg1":"582.0","t2eg2":"439.0","t2egsum1":"1021.0","t2dg1":"2551.0","t2dg2":"1653.0","t2dgsum2":"4204.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"09_10","t1eg1":"369.0","t1eg2":"512.0","t1eg3":"0.0","t1eg4":"0.0","t1egsum1":"881.0","t1dg1":"0.0","t1dg2":"1391.0","t1dg3":"1204.0","t1dg4":"1254.0","t1dg5":"214.0","t1dg6":"0.0","t1dgsum1":"4063.0","t2eg1":"480.0","t2eg2":"716.0","t2egsum1":"1196.0","t2dg1":"1488.0","t2dg2":"1225.0","t2dgsum2":"2713.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"10_11","t1eg1":"300.0","t1eg2":"849.0","t1eg3":"337.0","t1eg4":"213.0","t1egsum1":"1699.0","t1dg1":"0.0","t1dg2":"1146.0","t1dg3":"1172.0","t1dg4":"1401.0","t1dg5":"221.0","t1dg6":"0.0","t1dgsum1":"3940.0","t2eg1":"40.0","t2eg2":"389.0","t2egsum1":"429.0","t2dg1":"1292.0","t2dg2":"1323.0","t2dgsum2":"2615.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"11_12","t1eg1":"1094.0","t1eg2":"1027.0","t1eg3":"815.0","t1eg4":"518.0","t1egsum1":"3454.0","t1dg1":"0.0","t1dg2":"947.0","t1dg3":"974.0","t1dg4":"1103.0","t1dg5":"186.0","t1dg6":"0.0","t1dgsum1":"3210.0","t2eg1":"498.0","t2eg2":"467.0","t2egsum1":"965.0","t2dg1":"1141.0","t2dg2":"1032.0","t2dgsum2":"2173.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"12_13","t1eg1":"435.0","t1eg2":"828.0","t1eg3":"634.0","t1eg4":"634.0","t1egsum1":"2531.0","t1dg1":"0.0","t1dg2":"851.0","t1dg3":"963.0","t1dg4":"1066.0","t1dg5":"143.0","t1dg6":"0.0","t1dgsum1":"3023.0","t2eg1":"734.0","t2eg2":"787.0","t2egsum1":"1521.0","t2dg1":"1200.0","t2dg2":"1076.0","t2dgsum2":"2276.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"13_14","t1eg1":"880.0","t1eg2":"1081.0","t1eg3":"249.0","t1eg4":"249.0","t1egsum1":"2459.0","t1dg1":"0.0","t1dg2":"857.0","t1dg3":"1006.0","t1dg4":"1141.0","t1dg5":"175.0","t1dg6":"0.0","t1dgsum1":"3179.0","t2eg1":"947.0","t2eg2":"1014.0","t2egsum1":"1961.0","t2dg1":"1431.0","t2dg2":"1139.0","t2dgsum2":"2570.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"14_15","t1eg1":"1407.0","t1eg2":"1444.0","t1eg3":"490.0","t1eg4":"361.0","t1egsum1":"3702.0","t1dg1":"0.0","t1dg2":"752.0","t1dg3":"799.0","t1dg4":"911.0","t1dg5":"147.0","t1dg6":"0.0","t1dgsum1":"2609.0","t2eg1":"1910.0","t2eg2":"1730.0","t2egsum1":"3640.0","t2dg1":"1495.0","t2dg2":"1199.0","t2dgsum2":"2694.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"15_16","t1eg1":"775.0","t1eg2":"1019.0","t1eg3":"546.0","t1eg4":"546.0","t1egsum1":"2886.0","t1dg1":"0.0","t1dg2":"1003.0","t1dg3":"807.0","t1dg4":"820.0","t1dg5":"145.0","t1dg6":"0.0","t1dgsum1":"2775.0","t2eg1":"1901.0","t2eg2":"1193.0","t2egsum1":"3094.0","t2dg1":"923.0","t2dg2":"672.0","t2dgsum2":"1595.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"16_17","t1eg1":"1895.0","t1eg2":"1241.0","t1eg3":"319.0","t1eg4":"319.0","t1egsum1":"3774.0","t1dg1":"0.0","t1dg2":"1030.0","t1dg3":"744.0","t1dg4":"697.0","t1dg5":"95.0","t1dg6":"0.0","t1dgsum1":"2566.0","t2eg1":"2116.0","t2eg2":"1655.0","t2egsum1":"3771.0","t2dg1":"1557.0","t2dg2":"861.0","t2dgsum2":"2418.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"17_18","t1eg1":"805.0","t1eg2":"816.0","t1eg3":"190.0","t1eg4":"190.0","t1egsum1":"2001.0","t1dg1":"0.0","t1dg2":"971.0","t1dg3":"755.0","t1dg4":"755.0","t1dg5":"88.0","t1dg6":"0.0","t1dgsum1":"2569.0","t2eg1":"2529.0","t2eg2":"1536.0","t2egsum1":"4065.0","t2dg1":"2626.0","t2dg2":"2112.0","t2dgsum2":"4738.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"18_19","t1eg1":"1891.0","t1eg2":"1056.0","t1eg3":"127.0","t1eg4":"127.0","t1egsum1":"3201.0","t1dg1":"0.0","t1dg2":"850.0","t1dg3":"867.0","t1dg4":"961.0","t1dg5":"126.0","t1dg6":"0.0","t1dgsum1":"2804.0","t2eg1":"2419.0","t2eg2":"1694.0","t2egsum1":"4113.0","t2dg1":"2136.0","t2dg2":"2020.0","t2dgsum2":"4156.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"19_20","t1eg1":"1270.0","t1eg2":"1075.0","t1eg3":"561.0","t1eg4":"257.0","t1egsum1":"3163.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"1633.0","t1dg4":"1065.0","t1dg5":"174.0","t1dg6":"0.0","t1dgsum1":"2872.0","t2eg1":"1203.0","t2eg2":"1616.0","t2egsum1":"2819.0","t2dg1":"2872.0","t2dg2":"0.0","t2dgsum2":"2872.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"20_21","t1eg1":"1486.0","t1eg2":"609.0","t1eg3":"814.0","t1eg4":"96.0","t1egsum1":"3005.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"1846.0","t1dg4":"0.0","t1dg5":"133.0","t1dg6":"0.0","t1dgsum1":"1979.0","t2eg1":"1459.0","t2eg2":"938.0","t2egsum1":"2397.0","t2dg1":"1272.0","t2dg2":"0.0","t2dgsum2":"1272.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"21_22","t1eg1":"763.0","t1eg2":"895.0","t1eg3":"435.0","t1eg4":"435.0","t1egsum1":"2528.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"1164.0","t1dg4":"0.0","t1dg5":"102.0","t1dg6":"0.0","t1dgsum1":"1266.0","t2eg1":"1857.0","t2eg2":"807.0","t2egsum1":"2664.0","t2dg1":"577.0","t2dg2":"0.0","t2dgsum2":"577.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"22_23","t1eg1":"1183.0","t1eg2":"1262.0","t1eg3":"880.0","t1eg4":"386.0","t1egsum1":"3711.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"631.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"631.0","t2eg1":"1046.0","t2eg2":"467.0","t2egsum1":"1513.0","t2dg1":"115.0","t2dg2":"0.0","t2dgsum2":"115.0","tmp1":"","tmp2":""},{"adate":"20260430","atime":"23_00","t1eg1":"101.0","t1eg2":"0.0","t1eg3":"213.0","t1eg4":"0.0","t1egsum1":"314.0","t1dg1":"0.0","t1dg2":"0.0","t1dg3":"243.0","t1dg4":"0.0","t1dg5":"0.0","t1dg6":"0.0","t1dgsum1":"243.0","t2eg1":"1374.0","t2eg2":"0.0","t2egsum1":"1374.0","t2dg1":"2.0","t2dg2":"0.0","t2dgsum2":"2.0","tmp1":"","tmp2":""},{"adate":"합계","atime":"합계","t1eg1":"19854.0","t1eg2":"15902.0","t1eg3":"9726.0","t1eg4":"5905.0","t1egsum1":"51387.0","t1dg1":"0.0","t1dg2":"13928.0","t1dg3":"21713.0","t1dg4":"14731.0","t1dg5":"2608.0","t1dg6":"0.0","t1dgsum1":"52980.0","t2eg1":"24990.0","t2eg2":"20090.0","t2egsum1":"45080.0","t2dg1":"30580.0","t2dg2":"19609.0","t2dgsum2":"50189.0","tmp1":"","tmp2":""}]}}}

,adate,atime,T1(1),T1(2),T1(3),T1(4),T1(5),T1(6),T1,T2(A),T2(B),T2
0,20260430,00_01,0,0,496,0,0,0,496,0,0,0
1,20260430,01_02,0,0,190,0,0,0,190,0,0,0
2,20260430,02_03,0,0,56,0,0,0,56,4,0,4
3,20260430,03_04,0,0,157,0,0,0,157,73,0,73
4,20260430,04_05,0,0,905,0,0,0,905,687,0,687
5,20260430,05_06,0,359,1888,0,98,0,2345,1522,1255,2777
6,20260430,06_07,0,1002,902,1163,167,0,3234,2651,2025,4676
7,20260430,07_08,0,1372,1124,1139,173,0,3808,2965,2017,4982
8,20260430,08_09,0,1397,1187,1255,221,0,4060,2551,1653,4204
9,20260430,09_10,0,1391,1204,1254,214,0,4063,1488,1225,2713
10,20260430,10_11,0,1146,1172,1401,221,0,3940,1292,1323,2615
11,20260430,11_12,0,947,974,1103,186,0,3210,1141,1032,2173
12,20260430,12_13,0,851,963,1066,143,0,3023,1200,1076,2276
13,20260430,13_14,0,857,1006,1141,175,0,3179,1431,1139,2570
14,20260430,14_15,0,752,799,911,147,0,2609,1495,1199,2694
15,20260430,15_16,0,1003,807,820,145,0,2775,923,672,1595
16,20260430,16_17,0,1030,744,697,95,0,2566,1557,861,2418
17,20260430,17_18,0,971,755,755,88,0,2569,2626,2112,4738
18,20260430,18_19,0,850,867,961,126,0,2804,2136,2020,4156
19,20260430,19_20,0,0,1633,1065,174,0,2872,2872,0,2872
20,20260430,20_21,0,0,1846,0,133,0,1979,1272,0,1272
21,20260430,21_22,0,0,1164,0,102,0,1266,577,0,577
22,20260430,22_23,0,0,631,0,0,0,631,115,0,115
23,20260430,23_00,0,0,243,0,0,0,243,2,0,2
24,합계,합계,0,13928,21713,14731,2608,0,52980,30580,19609,50189